name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
    - name: Run iOS tests
      run: xcodebuild test -scheme ViewKit -destination platform="iOS Simulator,name=iPhone 11 Pro,OS=14.0"
    - name: Run tvOS tests
      run: xcodebuild test -scheme ViewKit -destination platform="tvOS Simulator,name=Apple TV 4K,OS=14.0"            
